#!/usr/bin/env python3
"""Answer one question about regenerated transcripts: did the protocol move?

When a newer Mojo toolchain regenerates `tests/snapshots/protocol/`, every
transcript differs from the committed baseline whether or not the runner
behaves differently, because line one of each transcript stamps the toolchain
that wrote it. That one difference is the toolchain's own identity and is
uninteresting; anything else — a changed byte of runner output, a different
`os-arch` or normalizer segment, a transcript that appeared or vanished — is
the protocol drift this exists to catch.

So the tolerance is deliberately narrow: exactly the `mojo <ver> (<commit>)`
span of the header is rewritten from the baseline's toolchain to the
candidate's before comparing, and the comparison itself is delegated whole to
`scripts.checks.transcript_compare`, which already owns file-set equality,
byte equality and per-file diffs for this repository's snapshot trees. There
is no second implementation of directory diffing here to drift from that one.

The other deliberate asymmetry is raise versus classify. A candidate that
writes an unreadable header has changed observable behaviour and is drift. A
*committed baseline* that does not parse is a broken repository, not a verdict
about a toolchain: it raises, because a corrupted baseline quietly classified
as drift would look identical to a healthy toolchain day in the canary's
output, and a canary that reports on its own corruption is worse than none.
"""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import TYPE_CHECKING

from scripts.checks.transcript_compare import compare_directories


if TYPE_CHECKING:
    from pathlib import Path


PASS = "PASS"  # noqa: S105 - a classification name, not a secret
PROTOCOL_DRIFT = "PROTOCOL_DRIFT"

# The bare newline-separated filename list beside the transcripts. It carries
# no header, so the identity walk must never try to parse it.
MANIFEST_NAME = "MANIFEST.txt"

# Line one as `scripts/gen_transcripts.py` writes it. Kept as strict as the
# generator's own `mojo --version` pattern: a header that has drifted into
# some other shape is not something to guess at.
_HEADER_IDENTITY = re.compile(
    r"# generated by scripts/gen_transcripts\.py — mojo (\S+) \(([0-9a-f]+)\),"
)


@dataclass(frozen=True)
class ToolchainIdentity:
    """The toolchain a transcript header claims wrote it."""

    version: str
    commit: str


@dataclass(frozen=True)
class CompareResult:
    """A classification of one baseline-versus-candidate transcript pair."""

    classification: str
    detail: str


def _identity_text(identity: ToolchainIdentity) -> str:
    """Render the header span that the comparison is allowed to rewrite."""
    return f"mojo {identity.version} ({identity.commit})"


def parse_header_identity(transcript_path: Path) -> ToolchainIdentity:
    """Read the toolchain identity out of a transcript's first line.

    Args:
        transcript_path: A generated transcript. Never `MANIFEST.txt`, which
            is a bare filename list with no header and would always fail here.

    Returns:
        The version and commit named in the header.

    Raises:
        ValueError: The first line is not a generated transcript header.
        OSError: The file cannot be read.
    """
    with transcript_path.open(encoding="utf-8", errors="surrogateescape") as handle:
        header = handle.readline()
    match = _HEADER_IDENTITY.match(header)
    if match is None:
        shown = header.rstrip("\n")
        raise ValueError(
            f"unreadable transcript header in {transcript_path}: {shown!r}"
        )
    return ToolchainIdentity(match.group(1), match.group(2))


def transcript_files(root: Path) -> list[Path]:
    """List every generated transcript under a snapshot tree, sorted.

    `MANIFEST.txt` at the root is excluded because it has no header; anything
    else is included, so that the identity walk sees the whole tree. Sampling
    one file instead would let a malformed transcript that happens to be
    byte-identical on both sides pass unexamined.

    Args:
        root: A snapshot tree. A path that does not exist is not an error
            here; it simply holds no transcripts, and the callers that care
            (`side_identity`, and `compare_directories` for the byte
            comparison) each report it in their own terms.

    Returns:
        The transcript paths, sorted, empty when there are none.
    """
    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file() and path.relative_to(root).as_posix() != MANIFEST_NAME
    )


def side_identity(root: Path) -> ToolchainIdentity:
    """Determine the single toolchain that wrote a whole snapshot tree.

    Every transcript is parsed and every identity must agree: one tree is the
    product of exactly one generator run, and a tree that disagrees with
    itself has no identity to substitute.

    Args:
        root: A snapshot tree.

    Returns:
        The identity shared by every transcript in the tree.

    Raises:
        ValueError: The tree holds no transcripts at all (an empty or missing
            side has nothing to say, and must not be mistaken for agreement),
            a header does not parse, or two headers disagree.
        OSError: A transcript cannot be read.
    """
    transcripts = transcript_files(root)
    if not transcripts:
        raise ValueError(f"no transcripts under {root} to identify a toolchain from")
    first_path = transcripts[0]
    identity = parse_header_identity(first_path)
    for path in transcripts[1:]:
        other = parse_header_identity(path)
        if other != identity:
            raise ValueError(
                f"{root} names two toolchains: "
                f"{_identity_text(identity)} in {first_path.name}, "
                f"{_identity_text(other)} in {path.name}"
            )
    return identity


def compare_transcript_dirs(pinned: Path, candidate: Path) -> CompareResult:
    """Classify a candidate toolchain's transcripts against the committed ones.

    Args:
        pinned: The committed baseline tree, written by the pinned toolchain.
        candidate: A tree regenerated by the candidate toolchain.

    Returns:
        `PASS` when the two trees differ by nothing but the toolchain
        identity, otherwise `PROTOCOL_DRIFT` carrying the first difference —
        a missing or unexpected transcript, an unreadable candidate header, or
        a unified diff of the first file whose bytes moved.

    Raises:
        ValueError: The baseline tree is empty, unreadable or inconsistent.
            That is a defect in this repository rather than a fact about the
            candidate toolchain, so it is never reported as a classification.
        OSError: A transcript cannot be read.
    """
    pinned_identity = side_identity(pinned)
    try:
        candidate_identity = side_identity(candidate)
    except ValueError as error:
        return CompareResult(PROTOCOL_DRIFT, str(error))

    replacement = (
        _identity_text(pinned_identity).encode("utf-8"),
        _identity_text(candidate_identity).encode("utf-8"),
    )
    comparison = compare_directories(pinned, candidate, replacement=replacement)
    if comparison.errors:
        return CompareResult(PROTOCOL_DRIFT, comparison.errors[0])
    return CompareResult(
        PASS,
        f"{_identity_text(pinned_identity)} -> "
        f"{_identity_text(candidate_identity)}: "
        f"{len(comparison.changed_files)} transcript(s) differ by that "
        "identity alone",
    )
