"""Smoke test: parse every committed transcript from Mojo and reconcile counts.

This is a REFERENCE mini-parser — the seed of the real report parser a later
phase builds — and it exists to prove two things at once: that the transcript
format is machine-parseable from Mojo using only `split`/`startswith` (no byte
indexing), and that a parser which merely reads the envelope is not enough. For
every scenario that carries a report it anchors on the LAST `Running <N> tests
for` line (the noisy fixture prints a report-lookalike line BEFORE the real
report, so first-match scanning would double-count) and reconciles the declared
count, the per-test rows, and the `Summary` tallies against each other. A parser
that "successfully" reads garbage must fail here.

Transcripts are enumerated via MANIFEST.txt, never a directory listing, so a
snapshot that is present on disk but missing from the manifest cannot hide.
"""
from std.testing import assert_equal, assert_true, TestSuite

comptime TX_DIR = "tests/snapshots/protocol/"


def _read(path: String) raises -> String:
    return open(path, "r").read()


def _lines(text: String) -> List[String]:
    var out = List[String]()
    for line in text.split("\n"):
        out.append(String(line))
    return out^


def _manifest() raises -> List[String]:
    var names = List[String]()
    for line in _read(TX_DIR + "MANIFEST.txt").split("\n"):
        var s = String(String(line).strip())
        if s.byte_length() > 0:
            names.append(s)
    return names^


def _index_of(lines: List[String], target: String) -> Int:
    for i in range(len(lines)):
        if lines[i] == target:
            return i
    return -1


def _last_running(lines: List[String], end: Int) -> Int:
    var idx = -1
    for i in range(end):
        if lines[i].startswith("Running ") and (" tests for " in lines[i]):
            idx = i
    return idx


def _stderr_marker(lines: List[String]) -> Int:
    # The report lives in the stdout section only; scanning must stop at the
    # stderr marker so a report-grammar lookalike in captured stderr is never
    # folded into the stdout tally.
    var i = _index_of(lines, "--- stderr ---")
    return len(lines) if i < 0 else i


def _first_int(field: String) raises -> Int:
    return Int(String(String(field).split(" ")[0]))


def test_manifest_lists_every_scenario() raises:
    var names = _manifest()
    # 18 protocol scenarios plus the native-skip scenarios (default, skip-all,
    # only-native).
    assert_equal(len(names), 21)
    var have_crash = False
    var have_only_unknown = False
    for n in names:
        if n == "crashing--default.txt":
            have_crash = True
        if n == "passing--only-unknown.txt":
            have_only_unknown = True
    assert_true(have_crash)
    assert_true(have_only_unknown)


def test_every_transcript_has_a_well_formed_envelope() raises:
    for name in _manifest():
        var lines = _lines(_read(TX_DIR + name))
        # Header, cmd, termination, and the stdout marker sit at fixed offsets.
        assert_true(
            lines[0].startswith("# generated by scripts/gen_transcripts.py")
        )
        assert_true("normalizer v1" in lines[0])
        assert_true("fixture " in lines[0])
        assert_true("scenario " in lines[0])
        # The mojo version must be present and non-empty.
        var ver = String(String(lines[0].split(" mojo ")[1]).split(" ")[0])
        assert_true(ver.byte_length() > 0)
        assert_true(lines[1].startswith("cmd: <BIN>"))
        assert_true(lines[2].startswith("termination: "))
        assert_equal(lines[3], "--- stdout ---")
        # The stderr marker must follow the stdout marker.
        assert_true(_index_of(lines, "--- stderr ---") > 3)


def test_report_counts_reconcile() raises:
    var checked = 0
    for name in _manifest():
        var lines = _lines(_read(TX_DIR + name))
        var stderr_i = _stderr_marker(lines)
        var anchor = _last_running(lines, stderr_i)
        if anchor < 0:
            continue  # error/crash scenarios carry no report block

        var declared = _first_int(
            String(lines[anchor].removeprefix("Running "))
        )

        var rows_pass = 0
        var rows_fail = 0
        var rows_skip = 0
        var summary_total = -1
        var sum_pass = -1
        var sum_fail = -1
        var sum_skip = -1

        # Scan only the report block — from the anchor to the stderr marker. A
        # report-lookalike a test printed earlier (before the anchor) or anything
        # in captured stderr (after the marker) must NOT be counted.
        for i in range(anchor, stderr_i):
            var ln = lines[i]
            if ln.startswith("    PASS [ "):
                rows_pass += 1
            elif ln.startswith("    FAIL [ "):
                rows_fail += 1
            elif ln.startswith("    SKIP [ "):
                rows_skip += 1
            elif ln.startswith("Summary [ "):
                var total_field = String(String(ln).split(" tests run:")[0])
                var toks = total_field.split(" ")
                summary_total = Int(String(toks[len(toks) - 1]))
                var tallies = String(String(ln).split("tests run: ")[1]).split(
                    " , "
                )
                sum_pass = _first_int(String(tallies[0]))
                sum_fail = _first_int(String(tallies[1]))
                sum_skip = _first_int(String(tallies[2]))

        assert_true(summary_total >= 0)
        var rows_total = rows_pass + rows_fail + rows_skip
        # declared == summary total == rows == passed+failed+skipped
        assert_equal(declared, summary_total)
        assert_equal(rows_total, summary_total)
        assert_equal(rows_pass, sum_pass)
        assert_equal(rows_fail, sum_fail)
        assert_equal(rows_skip, sum_skip)
        checked += 1

    # The default, skip-all, selection, and skipped scenarios all carry reports.
    assert_true(checked >= 6)


def test_noisy_impostor_precedes_the_real_report() raises:
    # The report-lookalike line the noisy fixture PRINTS must survive the
    # normalizer byte-exact AND sit before the anchor, so a parser that anchors
    # on the last `Running` line never mistakes it for a real result row.
    var lines = _lines(_read(TX_DIR + "noisy--default.txt"))
    var anchor = _last_running(lines, _stderr_marker(lines))
    assert_true(anchor > 0)
    var impostor = _index_of(lines, "    PASS [ 0.001 ] fake_impostor")
    assert_true(impostor >= 0)
    assert_true(impostor < anchor)


def test_tripwire_crash_terminates_by_signal() raises:
    # Pins the crashing-default snapshot: the crash dies by SIGNAL,
    # exactly as committed, and the ABORT line survives normalization on stdout.
    var text = _read(TX_DIR + "crashing--default.txt")
    var lines = _lines(text)
    assert_equal(String(lines[2].removeprefix("termination: ")), "signal 4")
    assert_true("ABORT: <REPO>/tests/fixtures/protocol/crashing.mojo" in text)
    assert_true("<STACK-DUMP>" in text)


def test_tripwire_only_unknown_error_phrase() raises:
    # Pins the passing-only-unknown snapshot's stale-name error.
    var text = _read(TX_DIR + "passing--only-unknown.txt")
    assert_true("explicitly allowed test not found in suite" in text)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
